// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-lXD_Rl9Lj6XJdsRwYsxypMOXtMeAQQ',
    appId: '1:483693928740:web:d7396dd177d5c2eb9fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    authDomain: 'chatapp-c2808.firebaseapp.com',
    storageBucket: 'chatapp-c2808.appspot.com',
    measurementId: 'G-ZTP5Y00KBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV6qur0TQN2S5YaqXkO3r2d6axxhXInTY',
    appId: '1:483693928740:android:3dcc6b16d75cf9c99fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    storageBucket: 'chatapp-c2808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qbAPhpUGqZp6CwWmmgalR0rr_3A8YM4',
    appId: '1:483693928740:ios:4e84e3103cf5f0019fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    storageBucket: 'chatapp-c2808.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6qbAPhpUGqZp6CwWmmgalR0rr_3A8YM4',
    appId: '1:483693928740:ios:4e84e3103cf5f0019fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    storageBucket: 'chatapp-c2808.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa-lXD_Rl9Lj6XJdsRwYsxypMOXtMeAQQ',
    appId: '1:483693928740:web:283825d0b05209159fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    authDomain: 'chatapp-c2808.firebaseapp.com',
    storageBucket: 'chatapp-c2808.appspot.com',
    measurementId: 'G-C3QL95KZTX',
  );
}
