// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-lXD_Rl9Lj6XJdsRwYsxypMOXtMeAQQ',
    appId: '1:483693928740:web:d7396dd177d5c2eb9fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    authDomain: 'chatapp-c2808.firebaseapp.com',
    storageBucket: 'chatapp-c2808.appspot.com',
    measurementId: 'G-ZTP5Y00KBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV6qur0TQN2S5YaqXkO3r2d6axxhXInTY',
    appId: '1:483693928740:android:55ae3949ece6a03b9fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    storageBucket: 'chatapp-c2808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qbAPhpUGqZp6CwWmmgalR0rr_3A8YM4',
    appId: '1:483693928740:ios:bb1433b1e6cc84259fd3b1',
    messagingSenderId: '483693928740',
    projectId: 'chatapp-c2808',
    storageBucket: 'chatapp-c2808.appspot.com',
    iosClientId: '483693928740-s0oae5jdfg31aiolhumcfgp29bqq0v9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
